name: aimless2021
main: com.github.xenon.aimless.plugin.AimlessPlugin
version: 1.0
api-version: '1.17'
commands:
  aimless:
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.20
  - org.jetbrains.kotlin:kotlin-reflect:1.5.20
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0
  - org.mariuszgromada.math:MathParser.org-mXparser:4.4.2